[package]
name = "arg_parse"
version = "1.0.0"
edition = "2021"
authors = ["Cameron Barnes <cameron_barnes@outlook.com>"]
repository = "https://github.com/CameronBarnes/arg_parse"
categories = ["command-line-interface", "config"]

[dependencies]
